version: '3.3'

services: 
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: wpdb
      MYSQL_USER: wpuser    
      MYSQL_PASSWORD: wppass    
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql
      - ./db/script:/docker-entrypoint-init.db.d
    networks:
      - back
  api:
    build: "./src"
    restart: 'no'
    depends_on:
      - db
    ports:
      - 8080:80
    networks:
      - back
    volumes: 
      - ./src/wp-admin/src:/var/www/html/admin/wp-content/themes
      - ./src/api/src:/var/www/html/api
      - ./config/laravel.conf:/etc/apache2/sites-available/api.conf
  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8888:8080
    networks:
      - back
networks:
  back:
    driver: bridge
  
volumes:
  db: